# Generated by Django 4.2.5 on 2023-10-13 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('ID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('num', models.IntegerField()),
                ('nItems', models.IntegerField(default=0)),
                ('lecturer', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('info', models.TextField(max_length=3000)),
                ('lecturer_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('sem_year', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Regis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('stu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
